

[31m

*** ERROR ***
/home/clr56/Documents/MechFail/input/Draft2/crackpressure/fixedBoundary/nonref.i:358: missing closing '[]' for section[39m


[New LWP 29603]
[Thread debugging using libthread_db enabled]
0x00000031ef4ac86d in waitpid () from /lib64/libc.so.6
To enable execution of this file add
	add-auto-load-safe-path /opt/moose-compilers/gcc_new/lib64/libstdc++.so.6.0.21-gdb.py
line to your configuration file "/home/clr56/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/clr56/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
#0  0x00000031ef4ac86d in waitpid () from /lib64/libc.so.6
#1  0x00000031ef43e479 in do_system () from /lib64/libc.so.6
#2  0x00000031ef43e7b0 in system () from /lib64/libc.so.6
#3  0x00007f8e57fce569 in libMesh::print_trace(std::basic_ostream<char, std::char_traits<char> >&) () from /home/clr56/projects/moose/scripts/../libmesh/installed/lib/libmesh_opt.so.0
#4  0x00007f8e5993f6b7 in moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /home/clr56/projects/moose/framework/libmoose-opt.so.0
#5  0x00007f8e598fc6f4 in _Z10mooseErrorIJPKcEEvDpOT_ () from /home/clr56/projects/moose/framework/libmoose-opt.so.0
#6  0x00007f8e59d11acc in Parser::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /home/clr56/projects/moose/framework/libmoose-opt.so.0
#7  0x00007f8e598f96da in MooseApp::setupOptions() () from /home/clr56/projects/moose/framework/libmoose-opt.so.0
#8  0x00007f8e598efb45 in MooseApp::run() () from /home/clr56/projects/moose/framework/libmoose-opt.so.0
#9  0x00000000004105d3 in main ()
srun: error: _server_read: fd 17 error reading header: Connection reset by peer
srun: error: step_launch_notify_io_failure: aborting, io error with slurmstepd on node 0
